# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          # Optional service account key to use for authentication to GCP. This should be the JSON
          # formatted private key which can be exported from the Cloud Console. The
          # value can be raw or base64-encoded.
          credentials: ${{ secrets.GCP_PRIVATE_KEY }}
          name: ${{ secrets.FUNCTION_NAME }}
          # Project to deploy the function in.
          project_id: toxictj
          region: ${{ secrets.FUNCTION_REGION }}
          source_dir: .
          # List of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2.
          env_vars: |
            DISCOVERY_API_KEY=${{ secrets.DISCOVERY_API_KEY }},
            DISCOVERY_URL=${{ secrets.DISCOVERY_URL }},
            TJ_API_KEY=${{ secrets.TJ_API_KEY }},
            TJ_BOT_ID=${{ secrets.TJ_BOT_ID }},
            TJ_ADD_COMMENT_URL=${{ secrets.TJ_ADD_COMMENT_URL }}
          entry_point: handler
          runtime: nodejs14
          timeout: 60
          #memory_mb: 128
          max_instances: 1
